# Generated by Django 5.0.1 on 2026-02-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('total_updates', models.IntegerField(default=0, help_text='Total updates submitted')),
                ('flagged_count', models.IntegerField(default=0, help_text='Updates rejected as outliers')),
                ('flag_reason', models.CharField(blank=True, help_text='Most recent flag reason', max_length=256)),
            ],
            options={
                'verbose_name': 'Client Record',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='RoundHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_id', models.IntegerField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('n_updates', models.IntegerField(help_text='Number of clean updates used in aggregation')),
                ('n_flagged', models.IntegerField(help_text='Number of updates rejected as outliers')),
                ('global_loss', models.FloatField(blank=True, help_text='Optional loss after aggregation', null=True)),
            ],
            options={
                'verbose_name': 'Round History',
                'verbose_name_plural': 'Round Histories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
