# Generated by Django 5.0.1 on 2026-02-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelupdatelog',
            name='agg_mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelupdatelog',
            name='agg_rmse',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelupdatelog',
            name='local_mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelupdatelog',
            name='local_rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
