# Generated by Django 5.0.1 on 2026-02-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_add_metrics_to_updatelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmodel',
            name='best_mae',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='globalmodel',
            name='best_rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
