# Generated by Django 5.0.1 on 2026-02-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_add_quality_metrics_to_globalmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalmodel',
            name='accepted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='globalmodel',
            name='rejected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelupdatelog',
            name='base_version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='modelupdatelog',
            name='staleness',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='globalmodel',
            name='weights_path',
            field=models.CharField(max_length=256),
        ),
    ]
